name: Setup Node And Install Dependencies

runs:
  using: Composite
  steps:
    - name: Setup Node.js
      id: setup_nodejs
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version-file: ".tool-versions"
    - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ steps.setup_nodejs.outputs.node-version }}-lock-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
