name: Setup Node And Install Dependencies

runs:
  using: Composite
  steps:
    - name: Setup Node.js
      id: setup_nodejs
      uses: actions/setup-node@v4.0.2
      with:
        node-version-file: ".tool-versions"
    - uses: actions/cache@v4.0.2
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ steps.setup_nodejs.outputs.node-version }}-lock-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
